export const profile = {
 name: 'Rozario Washington', title: 'ENL / TESOL Educator', location: 'New York City',
 email: 'Rwashington19@schools.nyc.gov', linkedin: '', resume: '/Rozario_Washington_Resume_ENL.pdf',
 intro: 'Designing meaningful, accessible, and culturally responsive learning experiences for multilingual learners.',
 bio: ['I’m Rozario, a new ENL educator in New York City, pursuing my M.S. in TESOL at CUNY College of Staten Island. I bring experience supporting students and a belief that every learner deserves both access to challenging ideas and space to be themselves.', 'My undergraduate background in New Media Design shapes how I teach. Visual hierarchy, clear organization, and purposeful technology help me turn complex content into learning materials students can navigate with confidence.'],
 philosophy: [
 'I see multilingualism as an asset. Students arrive with languages, identities, experiences, and community knowledge that deserve a place in the classroom. I want those resources to become a foundation for learning.',
 'Access begins with intentional instruction. I use visuals, modeling, clear language, and strategic pacing to make input understandable. Sentence frames, graphic organizers, and differentiated tasks offer support without reducing the thinking students are asked to do.',
 'Language grows through meaningful use. Collaborative discussion, real-world questions, and connections to students’ lives create reasons to read, write, listen, and speak. Home-language planning and translanguaging help students develop ideas before expressing them in new ways.',
 'A safe classroom gives students room to take risks and be heard. I check understanding frequently, listen to student voice, and adjust instruction. As confidence and independence grow, I gradually release responsibility and remove supports students no longer need.'
 ],
 credentials: [
 {title:'NYS ESOL Transitional B', detail:'New York State · PreK–12', status:'Certification'},
 {title:'M.S. TESOL', detail:'CUNY College of Staten Island', status:'In progress'},
 {title:'B.S. New Media Design', detail:'Rochester Institute of Technology', status:'Undergraduate education'},
 {title:'DASA Training',detail:'Dignity for All Students Act workshop',status:'Completed'},
 {title:'Mandated Reporter Training',detail:'Mandated reporter workshop',status:'Completed'},
 {title:'FERPA / Student Privacy',detail:'Student privacy and confidentiality training',status:'Completed'},
 ],
 experience:[
 {period:'School-based experience',title:'Paraprofessional',org:'NYC Public Schools',text:'Individualized and small-group support, academic language practice, visual scaffolds, and collaboration with classroom teachers.'},
 {period:'2022–2024',title:'HEOP Mentor',org:'Rochester Institute of Technology',text:'Guidance and regular check-ins to support first-year students’ academic transition, confidence, and sense of belonging.'},
 {period:'2020',title:'Teaching Assistant',org:'Rochester Institute of Technology',text:'Instructional support, assessment and grading, and collaboration with faculty on active learning experiences.'}
 ]
};
export const navigation=['Home','About','Teaching','Portfolio','Credentials','Contact'];
export const principles=[
 {title:'Language',text:'Supporting academic language development while valuing students’ full linguistic repertoires.',icon:'languages'},
 {title:'Culture',text:'Connecting instruction to students’ identities, communities, experiences, and funds of knowledge.',icon:'globe'},
 {title:'Design',text:'Using visual communication and thoughtful scaffolds to make learning more accessible.',icon:'layers'}
];
export const strategies=[
 {title:'Comprehensible Input',text:'Visuals, modeling, gestures, chunking, and strategic pacing.',example:'Show a photograph, model a short explanation, and check understanding before adding new vocabulary.',icon:'eye'},
 {title:'Scaffolding',text:'Sentence frames, word banks, graphic organizers, and exemplars.',example:'Move from a completed model to a shared response, then invite students to explain independently.',icon:'layers'},
 {title:'Translanguaging',text:'The complete linguistic repertoire as a resource for learning.',example:'Invite home-language brainstorming and bilingual labels, followed by supported English rehearsal.',icon:'languages'},
 {title:'Academic Language',text:'Vocabulary, language functions, structured talk, reading, and writing.',example:'Teach the language of explaining, narrating, and arguing alongside the content of a lesson.',icon:'message'},
 {title:'Culturally Responsive Teaching',text:'Students’ identities and lived experiences as a starting point.',example:'Offer meaningful choices and connections without asking students to represent an entire culture.',icon:'globe'},
 {title:'Assessment',text:'Observation, conferencing, student work, and frequent checks.',example:'Separate conceptual understanding from English proficiency and use evidence to plan the next step.',icon:'check'}
];
export const toolkit=[
 ['WIDA','Connect language development to the language students use in content learning.'],
 ['SIOP','Plan explicit content and language objectives, interaction, and review.'],
 ['See–Think–Wonder','Start with observation, make thinking visible, and build questions.'],
 ['Sentence Frames','Make a language pattern available, then gradually release the support.'],
 ['Graphic Organizers','Make relationships, sequences, and ideas visible before writing.'],
 ['Visual Scaffolds','Use labeled images and models alongside spoken and written language.'],
 ['Vocabulary Instruction','Teach words through meaningful use, visuals, and repeated encounters.'],
 ['Cooperative Learning','Give partners a shared goal and equitable opportunities to contribute.'],
 ['Translanguaging','Invite students to use all their languages to develop and communicate ideas.'],
 ['Formative Assessment','Use frequent low-stakes checks to decide what students need next.'],
 ['Culturally Responsive Teaching','Build on students’ identities, experiences, and community knowledge.'],
 ['Differentiation','Vary the support and response mode while preserving the learning goal.'],
 ['Gradual Release','Move from modeling to shared practice to increasing independence.'],
 ['Funds of Knowledge','Connect instruction to knowledge developed in homes and communities.'],
 ['Multimodal Learning','Offer meaningful ways to learn through language, images, movement, and sound.']
];
export type Lesson={slug:string;number:string;title:string;subtitle:string;band:string;grade:string;subject:string;level:string;duration:string;description:string;imageKey:string;pdf?:string;status:string;tags:string[];standard:string;languageUse:string;challenge:string;context:string;contentObjective:string;languageObjective:string;frames:[string,string][];sequence:[string,string][];activity:string;assessment:string;reflection:string;gallery:[string,string][];note?:string};
export const lessons:Lesson[]=[
 {slug:'desert-detectives',number:'01',title:'Desert Detectives',subtitle:'Observe. Describe. Explain.',band:'Elementary',grade:'2',subject:'Science + ENL',level:'Emerging–Transitioning',duration:'60 minutes',description:'From noticing a habitat to explaining how an animal survives. Science made accessible through observation, images, and bilingual language supports.',imageKey:'desert',pdf:'Elementary_Desert_Detectives_ENL_Lesson.pdf',status:'Sample lesson · English + Spanish',tags:['See–Think–Wonder','Visual scaffolds','Sentence frames'],standard:'WIDA Standard 4: Language for Science',languageUse:'Explain',challenge:'How can students explain a scientific relationship while developing the language needed to describe it?',context:'Grade 2 learners explore habitats and animal survival. Photographs, partner talk, gestures, and bilingual labels create multiple entry points to the same science concept.',contentObjective:'Identify two desert characteristics and explain one way a desert animal survives.',languageObjective:'Describe an animal and connect a survival feature to its function using a supported oral or written explanation.',frames:[['The ___ has ___, which helps it ___.','El/La ___ tiene ___, lo que le ayuda a ___.'],['Because the desert is ___, the animal ___.','Como el desierto es ___, el animal ___.']],sequence:[['08 min · Notice','Use See–Think–Wonder with a desert photograph. Rehearse observations with a partner.'],['08 min · Build vocabulary','Match images and English–Spanish labels; say, gesture, and use each word.'],['14 min · Model together','Connect a camel’s fat-storing hump and a fennec fox’s large ears to their functions.'],['12 min · Investigate','Read an animal card together and complete an organizer.'],['18 min · Create and reflect','Make a survival poster, explain it, and complete an exit ticket.']],activity:'A mini survival poster includes an animal, a desert characteristic, an adaptation, and an explanatory sentence. Students may draw before writing and rehearse in either language.',assessment:'Check scientific accuracy and whether the explanation links a feature to survival. Record the amount of language support separately. Accept a written response, a drawing with oral explanation, or a recording.',reflection:'Observation lowers the language barrier at the start. Modeling reveals the reasoning, and partner rehearsal helps students move toward an independent explanation.',gallery:[['desert-5.webp','English–Spanish vocabulary and learning goals'],['desert-6.webp','Bilingual photo captions and language frames'],['desert-7.webp','Animal organizer, poster directions, and exit ticket']]},
 {slug:'stories-that-shape-us',number:'02',title:'Stories That Shape Us',subtitle:'Connect. Interpret. Create.',band:'Middle school',grade:'7',subject:'ELA + ENL',level:'Emerging–Expanding',duration:'60 minutes',description:'A meaningful object becomes the beginning of a story. Identity, multilingual planning, and a bilingual mentor text support narrative writing.',imageKey:'stories',pdf:'Middle_School_Stories_That_Shape_Us_ENL_Lesson.pdf',status:'Sample lesson · English + Spanish',tags:['Identity','Translanguaging','Narrative writing'],standard:'WIDA Standard 2: Language for Language Arts',languageUse:'Narrate',challenge:'How can students develop rich ideas without having to generate a story and solve every English-language demand at once?',context:'Grade 7 students begin a personal narrative unit. They can choose an object, place, or experience, or invent a character and event. Personal disclosure is always optional.',contentObjective:'Analyze how a narrative communicates identity and develop a short narrative about something meaningful.',languageObjective:'Use sequencing words, sensory details, and a statement of significance to tell a short story.',frames:[['___ is important to me because ___.','___ es importante para mí porque ___.'],['When ___ happened, I felt ___.','Cuando pasó ___, me sentí ___.']],sequence:[['12 min · Connect','Explore identity objects and brainstorm an identity web in any language.'],['10 min · Interpret','Read The Old Pot / La olla vieja and mark details, emotions, and sequence.'],['06 min · Model','Think aloud through the beginning, middle, and significance of a sketchbook narrative.'],['08 min · Rehearse','Tell a partner the story; the listener asks a clarifying question.'],['24 min · Draft and reflect','Write a supported paragraph, review the checklist, and reflect on helpful strategies.']],activity:'An identity web becomes a beginning–middle–end plan, then a short narrative. Include at least one sensory detail and an explanation of why the experience matters.',assessment:'Look for focus, significance, description, sequence, and clear communication. Respond with one strength and one actionable revision step. Assess ideas separately from scaffold use.',reflection:'Bilingual planning values students’ existing resources. Oral rehearsal makes it easier to organize a story before writing, while a fictional option protects privacy and choice.',gallery:[['stories-5.webp','Bilingual vocabulary and identity web prompts'],['stories-6.webp','The Old Pot / La olla vieja: paired mentor text'],['stories-7.webp','Bilingual narrative planner and reflection']]},
 {slug:'phones-in-school',number:'03',title:'Phones in School',subtitle:'Analyze. Discuss. Argue.',band:'High school',grade:'10',subject:'ELA / Civics + ENL',level:'Transitioning–Expanding',duration:'80 minutes',description:'Move beyond an initial opinion to a reasoned position. Source analysis and structured discussion make academic argumentation visible.',imageKey:'phones',pdf:'High_School_Phones_in_School_ENL_Lesson.pdf',status:'Sample lesson · English + Spanish',tags:['Source analysis','Academic discussion','Argumentation'],standard:'WIDA Standard 2: Language for Language Arts',languageUse:'Argue',challenge:'How can students distinguish an opinion from an argument and explain why evidence supports a claim?',context:'Grade 10 learners consider how a hypothetical school phone policy could balance learning and student needs. No particular viewpoint is required.',contentObjective:'Evaluate multiple perspectives and construct a defensible, evidence-based claim.',languageObjective:'State a claim, attribute evidence, explain reasoning, and respond to a counterclaim with academic connectors.',frames:[['According to ___, ___. This supports my claim because ___.','Según ___, ___. Esto respalda mi postura porque ___.'],['Some people argue ___. However, ___.','Algunas personas sostienen que ___. Sin embargo, ___.']],sequence:[['06 min · Take a position','Choose an initial position on an opinion continuum, with a private response option.'],['10 min · Model reasoning','Separate claim, evidence, and reasoning in a verified passage.'],['18 min · Evaluate sources','Compare a research source, student perspective, and policy example.'],['14 min · Discuss','Use roles and sentence stems to question, add evidence, and respond.'],['32 min · Argue and reflect','Draft an argument and explain whether evidence changed the initial position.']],activity:'A short argument includes a claim, accurate attributed evidence, reasoning, a fair counterclaim, and a rebuttal. Students can plan bilingually before producing an English draft.',assessment:'Score claim, evidence, reasoning, counterclaim, and language. Evaluate the quality of reasoning rather than agreement with the teacher. Record supports separately from task performance.',reflection:'The progression from opinion to evidence and discussion gives students a purpose for academic language. The challenge remains rigorous while the language becomes more accessible.',gallery:[['phones-5.webp','English–Spanish argument vocabulary'],['phones-6.webp','Source analysis and discussion prompts'],['phones-7.webp','Bilingual argument-writing scaffold']],note:'Teaching preparation: select and cite the three real source readings before teaching. The PDF includes source-selection guidance, not a completed source packet.'},
 {slug:'exploring-desert-environments',number:'04',title:'Exploring Desert Environments',subtitle:'See. Name. Wonder.',band:'Early elementary',grade:'K–1',subject:'Science + Language Development',level:'Entering–Emerging',duration:'3 short sessions',description:'An early-years unit concept using images, bilingual labels, talk, and a collaborative habitat poster.',imageKey:'desert',status:'Illustrative unit concept',tags:['Vocabulary','Picture-supported talk','Collaborative poster'],standard:'WIDA Standard 4: Language for Science',languageUse:'Inform + Explain',challenge:'How can beginning multilingual learners share observations before they can produce extended English?',context:'A hypothetical K–1 class explores a hot desert habitat. This is a sample unit concept, distinct from the completed Grade 2 lesson.',contentObjective:'Notice features of a desert and match a pictured animal to its habitat.',languageObjective:'Name a pictured feature and use “I see ___” or “The desert is ___” with visuals or partner support.',frames:[['I see ___.','Veo ___.'],['The desert is dry.','El desierto es seco.']],sequence:[['Session 1 · Notice','Use See–Think–Wonder and model picture-supported observations.'],['Session 2 · Name and connect','Practice desert/desierto, water/agua, and shade/sombra; sort animal and habitat cards.'],['Session 3 · Create','Work together on a habitat poster with bilingual labels and one oral explanation each.']],activity:'A collaborative poster combines drawings, labeled picture cards, and student dictation. Each learner contributes through pointing, naming, drawing, or a supported sentence.',assessment:'Use a child-friendly “I can notice / I can name / I can explain” check. Observe the understanding behind a point, drawing, or utterance before deciding what support comes next.',reflection:'Short repeated routines give young learners familiarity. Images and home-language connections support access while students build confidence participating in English.',gallery:[],note:'Illustrative concept: lesson slides, images, and a dedicated downloadable unit are not yet supplied. The completed Grade 2 desert PDF is available as a separate case study.'}
];
